# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    # Install dependencies for Headless Chrome
    - name: Install dependencies for Chrome
      run: sudo apt-get install -y libnss3 libxss1 libasound2 libatk-bridge2.0-0 libcups2 fonts-liberation libappindicator3-1 libgbm1

    # Build the application if necessary
    - run: npm run build --if-present

    # Run tests
    - name: Run tests
      env:
        CI: true
      run: npm test
